# Your Website Title
title: Alex Negulescu

# Your Website URL
url: 'https://alecs.negulescu.me'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-162928903-1
ga_cv: UA-162928903-1
ga_tag: G-CN3Q3FV4ZE

# Index page and Profile Information
name: Alex Negulescu
tagline: Sr DevOPS, SmartHome/IoT & Networking
pic: profile.png
description: Sr DevOPS, IoT, Integration, SmartHome, Networking, Reverse Engineering
description_tiny: 'Office: +40373747743'
email: alecs+filtered@negulescu.me
website: alecs.github.io # do not add http://
linkedin: alecsey
github: alecs
twitter: '@antis0cialul'
pdfcv: 'cv.pdf'

# Files or folders to be excluded
exclude: [gitbook_source_code/ gitbook/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap

gems:
  - jekyll-pdf
  - jekyll-sitemap
#  - wdm-0.1.1
